AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/ParameterLists:
  Max: 6

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
