# frozen_string_literal: true

module SmartIdRuby
  # Represents a Smart-ID callback URL and its associated one-time token
  # generated by the Smart-ID service for Web2App/device-link flows.
  class CallbackUrl
    attr_reader :url, :token

    def initialize(url:, token:)
      @url = url
      @token = token
    end

    def to_s
      url
    end
  end
end
